name: CI
on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: SSH Deploy
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_PRIVATE_KEY }}
                  port: 22
                  script: |
                      set -e

                      cd ./SubscriptionsPlusServer

                      git stash || true
                      git pull origin main

                      export DB_URL=${{ secrets.PROD_DB_URL }}

                      make migrate-up

                      cd ./scripts
                      bash pre_deploy
                      bash systemd
